# Generated by Django 5.1.6 on 2025-02-12 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Category_Reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.category'),
        ),
    ]
